App_1/urls.py
# from django.conf.urls import url
from App_1 import views
from django.urls import path

app_name = 'App_1'

urlpatterns = [
    path("",views.index, name="index"),
    path("keanu/", views.help, name='keanu'),
    path('form_1', views.knowledge_view, name='form'),
    path('form_2', views.for_user_view, name='form2')
]

App_2/urls.py
from App_2 import views
from django.urls import path

app_name = 'App_2'

urlpatterns = [
    path('', views.index, name='index'),
    path('other', views.other, name='other'),
    path('another', views.another, name='another'),
]

App_3/urls.py
from django.urls import path
from App_3 import views


app_name = 'App_3'

urlpatterns = [
    path('',views.index, name='index'),
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
]

Project_1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from App_1 import views
from App_3 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('App_1/', include('App_1.urls')),
    path('App_2/', include('App_2.urls')),
    path('App_3/', include('App_3.urls')),
    path('logout', views.user_logout, name='logout'),
]

App_1/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE )
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class for_user(models.Model):
    name = models.CharField(max_length=264, unique =False)
    job = models.CharField(max_length=264)

    def __str__(self):
        return str(self.name + ' has job: ' + self.job)
    
    

App_2/models.py
from django.db import models

# Create your models here.

App_3/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username
    

App_1/forms.py
from django import forms
from django.core import validators
from App_1.models import for_user

# MAKING OWN CUSTOM VALIDATION
def check_for_a(value):
    if value[0].lower() != 'a':
        raise forms.ValidationError('Name needs to start with a or A')

class Form_1(forms.Form):
    name = forms.CharField(validators=[check_for_a])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter email address again')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators = [validators.MaxLengthValidator(0)])

    # Cleaning all fields at once
    
    def clean(self):
        all_clean_data = super().clean() 
        # returns all data
        email = all_clean_data['email']
        v_email = all_clean_data['verify_email']
        
        # Checking if email matches
        if email!= v_email:
            raise forms.ValidationError('Email did not match')


class Form_2(forms.ModelForm):
    class Meta:
        model = for_user
        fields = '__all__'

App_3/forms.py
from django import forms
from django.contrib.auth.models import User
from App_3.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

App_1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from App_1.models import Topic, Webpage, AccessRecord
from . import forms
from App_1.forms import Form_2

# Create your views here.
# def index(request):
    # my_dict = {'insert_me':"Hello I am from views.py"}
    # return render(request, 'App_1/index.html', context=my_dict)

def help(keanu):
    k_dict = {'image':'image incoming '}
    return render(keanu, 'App_1/page2.html', context=k_dict)

def index(request):
    webpage_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpage_list}
    return render(request, 'App_1/index.html', context=date_dict)
    
def knowledge_view(request):
    form_1 = forms.Form_1()

    if request.method == 'POST':
        form_1 = forms.Form_1(request.POST) 

        if form_1.is_valid():
            print("VALIDATION SUCCESS ")
            print("NAME = " + form_1.cleaned_data['name'])
            print("EMAIL = "+ form_1.cleaned_data['email'])
            print("Text = " + form_1.cleaned_data['text'])
            



    for_form = {'form':form_1}
    return render (request, 'App_1/form_page.html', context=for_form)
    # return render (request, 'App_1/form_page.html', {'form':form})


def for_user_view(request):
    form = Form_2()

    if request.method == 'POST':
        form = Form_2(request.POST)

        if form.is_valid():
            form.save(commit=True)

    return render(request, 'App_1/for_user.html', {'form':form})

App_2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    # context_dict = {'text'}
    return render(request, 'App_2/index.html')

def other(request):
    return render(request, 'App_2/other.html')

def another(request):
    return render(request, 'App_2/another.html')

App_3/views.py
from django.shortcuts import render
from App_3.forms import UserForm, UserProfileInfoForm


from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect 
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'App_3/index.html')

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

                profile.save()


                registered = True

        else:
                print(user_form.errors, profile_form.errors)
        
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()



    # form_dict = {'user_form': user_form, 'profile_form':profile_form, 'registered':registered}
    # return render (request, 'App_3/registration.html',context=form_dict)
    return render (request, 'App_3/registration.html',
    {'user_form':user_form, 'profile_form':profile_form, 'registerd':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account has been deactivated')

        else:
            print('some user tried to login and failed')
            return HttpResponse('Invalid login Information')
    
    else:
        return render(request, 'App_3/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/APP_3/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <div class="container">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="navbar-brand"><a href="{% url 'App_3:index' %}">APP3_Index</a></li>
                <li class="nav-link"><a href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-link"><a href="{% url 'App_3:register' %}">Register</a></li>

                {% if user.is_authenticated %}

                <li class="nav-link"><a href="{% url 'logout' %}">Logout</a></li>

                {% else %}

                <li class="nav-link"><a href="{% url 'App_3:user_login' %}">Login</a></li>


                {% endif %}
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

templates/APP_3/index.html
{% extends 'App_3/base.html' %}


{% block body_block%}

<div class="container">

    <h1>This is Index.html of App_3.</h1>

</div>

{% endblock %}

templates/APP_3/login.html
{% extends 'App_3/base.html' %}

{% block body_block %}


<div class="container">

    <h1>LOGIN</h1>

    <form action="{% url 'App_3:user_login' %}" method="post"></form>
    {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" name="usernamer" placeholder="Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" value="Login">


</div>



{% endblock %}

templates/APP_3/registration.html
{% extends 'App_3/base.html' %}

{% block body_block %}

    <div>
        {% if registered %}
            <h1>Thank you for registering.</h1>

        {% else %}
            <h1>Please Register</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p}}
                {{ profile_form.as_p}}

                <input type="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/App_1/for_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" conStent="width=device-width, initial-scale=1.0">
    <title>Forms</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    <div class="continer">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success btn-lg" value="Submit">
        </form>
    </div>
</body>
</html>

templates/App_1/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forms</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    <div class="continer">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success btn-lg" value="Submit">
        </form>
    </div>
</body>
</html>

templates/App_1/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django_part_two</title>
    <link rel="stylesheet" href=" {% static "css/styles.css" %} ">
</head>
<body>
    <h1>Django level 2</h1>
    <h2>Access Records</h2>

    <div>
        {% if access_records %}
        
        <table>
            <thead>
                <th>Site Name</th>
                <th>Date Accessed</th>
            </thead>

            {% for a in access_records %}
            <tr>
                <td>{{ a.name }}</td>
                <td>{{ a.date }}</td>
            </tr>

            {% endfor %}
        </table>

        {% else %}

        <p>No Access Reocrds Found</p>

        {% endif %}
    </div>
    
</body>
</html>

templates/App_1/page2.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Keanu Reeves.</h1>
    <img src="{% static "images/keanu.jpg" %}" alt="Not Found hmm" >
</body>
</html>

templates/App_2/another.html
<!DOCTYPE html>

{% extends 'App_2/base.html' %}

    {% block body_block %}

    <h1>Welcome to <strong>Another</strong> Page.</h1>

    {% endblock %}

templates/App_2/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <ul class="navbar-nav">

                <li><a class="navbar-brand" href="#">BRAND</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index'%}">ADMIN</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'App_2:other'%}">OTHER</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'App_2:another'%}">ANOTHER</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'App_2:index'%}">Main Page</a></li>

            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}
        
        {% endblock %}



    </div>

</body>
</html>

templates/App_2/index.html
<!DOCTYPE html>

{% extends 'App_2/base.html' %}

    {% block body_block %}

    <h1>This is the index.html Page.</h1>

    {% endblock %}

templates/App_2/other.html
<!DOCTYPE html>
{% extends "App_2/base.html" %}

{% block body_block %}

    <h3>This is the <strong>Other</strong> Page.</h3>

    <li><a href="{% url 'App_2:another' %}">Another Page</a></li>
    <li><a href="{% url 'App_2:index' %}">Main</a></li>

{% endblock %}